export const endpoints = {
  login: "/auth/login",
  me: "/auth/eu",
  units: "/unidades",
  sectors: "/setores",
  departments: (sectorId: string) => `/setores/${sectorId}/departamentos`,
  users: "/usuarios",
  suppliers: "/fornecedores",
  bids: "/licitacoes",
  priceRecords: "/atas",
  priceRecordItems: (recordId: string) => `/atas/${recordId}/itens`,
  contracts: "/contratos",
  contractItems: (contractId: string) => `/contratos/${contractId}/itens`,
  contractsForRequest: "/contratos/para-solicitacao",
  workflows: (processType: string) => `/fluxos/${processType}`,
  requests: "/solicitacoes",
  processes: "/processos",
  audit: "/auditoria",
  emails: "/emails",
  assetLocations: "/patrimonio/locais",
  assetCategories: "/patrimonio/categorias",
  assetIntakes: "/patrimonio/remessas",
  assets: "/patrimonio/bens",
  inventories: "/patrimonio/inventarios",
  inventoryChecks: (inventoryId: string) => `/patrimonio/inventarios/${inventoryId}/conferencias`,
  closeInventory: (inventoryId: string) => `/patrimonio/inventarios/${inventoryId}/concluir`,
  assetTransfers: "/patrimonio/transferencias",
  transferAsset: (assetId: string) => `/patrimonio/bens/${assetId}/transferir`,
  transferAction: (id: string, acao: string) => `/patrimonio/transferencias/${id}/${acao}`,
  assetWriteOffs: "/patrimonio/baixas",
  writeOffAsset: (assetId: string) => `/patrimonio/bens/${assetId}/baixa`,
  // Almoxarifado
  warehouses: "/almoxarifado/almoxarifados",
  stockTypes: "/almoxarifado/tipos",
  warehouseBatches: (id: string) => `/almoxarifado/almoxarifados/${id}/lotes`,
  products: "/almoxarifado/produtos",
  stockSettings: "/almoxarifado/configuracao",
  stockLocations: "/almoxarifado/locais",
  localStock: (localId: string) => `/almoxarifado/locais/${localId}/estoque`,
  intakes: "/almoxarifado/remessas",
  batch: (id: string) => `/almoxarifado/lotes/${id}`,
  availability: (warehouseId: string) => `/almoxarifado/disponiveis/${warehouseId}`,
  stockRequests: "/almoxarifado/solicitacoes",
  stockRequestItems: (id: string) => `/almoxarifado/solicitacoes/${id}/itens`,
  stockRequestAction: (id: string, acao: string) => `/almoxarifado/solicitacoes/${id}/${acao}`,
  consumption: "/almoxarifado/consumo",
  returns: "/almoxarifado/devolucoes",

  // Módulo próprio, com prefixo próprio: o checklist atravessa os módulos e
  // não pertence a nenhum deles.
  checklists: "/checklists",
  checklistTemplates: "/checklists/modelos",
  consumptionReports: "/almoxarifado/relatorios",
  quality: "/almoxarifado/qualidade",
  answerReturn: (id: string) => `/almoxarifado/devolucoes/${id}/responder`,
  stockTransfers: "/almoxarifado/transferencias",
  adjustments: "/almoxarifado/ajustes",

  vehicles: "/frotas/veiculos",
  drivers: "/frotas/motoristas",
  trips: "/frotas/viagens",
  tripAction: (tripId: string, acao: string) => `/frotas/viagens/${tripId}/${acao}`,
  maintenances: "/frotas/manutencoes",
  closeMaintenance: (id: string) => `/frotas/manutencoes/${id}/encerrar`,
  refuels: (tripId: string) => `/frotas/viagens/${tripId}/abastecimentos`,
  refuel: (id: string) => `/frotas/abastecimentos/${id}`,
  fleetSchedule: "/frotas/agenda",
  fleetUsageReport: "/frotas/relatorios/uso",

  // Saúde: a ficha do pronto atendimento.
  healthUnits: "/saude/unidades",
  cnesMunicipalities: "/saude/unidades/cnes/municipios",
  cnesByMunicipality: (codigo: string) => `/saude/unidades/cnes/municipios/${codigo}`,
  patients: "/saude/pacientes",
  patientHistory: (id: string) => `/saude/pacientes/${id}/historico`,
  patientConditions: (id: string) => `/saude/pacientes/${id}/condicoes`,
  patientCondition: (id: string, condicaoId: string) =>
    `/saude/pacientes/${id}/condicoes/${condicaoId}`,
  visits: "/saude/atendimentos",
  visit: (id: string) => `/saude/atendimentos/${id}`,
  // Cada bloco da ficha é um ato próprio, com permissão própria: a URL
  // desenha a mesma divisão que o papel imprime.
  visitBlock: (id: string, bloco: string) => `/saude/atendimentos/${id}/${bloco}`,
  examResult: (id: string, exameId: string) =>
    `/saude/atendimentos/${id}/exames/${exameId}`,
  administrations: (itemId: string) => `/saude/itens-prescritos/${itemId}/administracoes`,

  // Programas de cuidado continuado. O catálogo tem endereço próprio porque
  // tem porta própria: quem o monta é o administrador, que não alcança
  // inscrito nenhum.
  programCatalog: "/saude/programas/catalogo",
  programTherapies: (id: string) => `/saude/programas/catalogo/${id}/terapias`,
  programTherapy: (id: string, terapiaId: string) =>
    `/saude/programas/catalogo/${id}/terapias/${terapiaId}`,
  programPeople: "/saude/programas/pessoas",
  programPerson: (id: string) => `/saude/programas/pessoas/${id}`,
  enrollments: "/saude/programas/inscritos",
  enrollmentStatus: (id: string) => `/saude/programas/inscritos/${id}/situacao`,
  indications: (id: string) => `/saude/programas/inscritos/${id}/indicacoes`,
  startTherapy: (id: string) => `/saude/programas/indicacoes/${id}/iniciar`,
  endTherapy: (id: string) => `/saude/programas/indicacoes/${id}/encerrar`,
  therapySessions: (id: string) => `/saude/programas/indicacoes/${id}/sessoes`,
  programTeam: (id: string) => `/saude/programas/${id}/equipe`,
  endTeamMember: (membroId: string) => `/saude/programas/equipe/${membroId}/encerrar`,
  programReport: (id: string) => `/saude/programas/${id}/relatorio`,
  programCuts: (id: string) => `/saude/programas/${id}/recortes`,
  programCut: (id: string) => `/saude/programas/recortes/${id}`,
} as const;
