export const endpoints = {
  login: "/auth/login",
  me: "/auth/eu",
  units: "/unidades",
  sectors: "/setores",
  departments: (sectorId: string) => `/setores/${sectorId}/departamentos`,
  users: "/usuarios",
  suppliers: "/fornecedores",
  bids: "/licitacoes",
  priceRecords: "/atas",
  priceRecordItems: (recordId: string) => `/atas/${recordId}/itens`,
  contracts: "/contratos",
  contractItems: (contractId: string) => `/contratos/${contractId}/itens`,
  workflows: (processType: string) => `/fluxos/${processType}`,
  requests: "/solicitacoes",
  processes: "/processos",
  audit: "/auditoria",
  assetLocations: "/patrimonio/locais",
  assetCategories: "/patrimonio/categorias",
  assetIntakes: "/patrimonio/remessas",
  assets: "/patrimonio/bens",
  inventories: "/patrimonio/inventarios",
  inventoryChecks: (inventoryId: string) => `/patrimonio/inventarios/${inventoryId}/conferencias`,
  closeInventory: (inventoryId: string) => `/patrimonio/inventarios/${inventoryId}/concluir`,
} as const;
